---
- hosts: myhosts
  name: PowerEdge iDRAC Get System Information
  gather_facts: False
  
  vars:
     idrac_user: root      
     idrac_passwd: calvin
     
  tasks:
  - name: get system info
    idrac: idrac_user={{idrac_user}} idrac_passwd={{idrac_passwd}} idrac_ip={{idrac_ip}} subsystem=System cmd={{item}}
    with_items:
      -Health
  