---
- hosts: myhosts
  name: PowerEdge iDRAC Get System Information
  gather_facts: False

  
  vars:
     idrac_user: root      
     idrac_passwd: calvin
  
  tasks: 

  - name: get firmware info
    idrac: idracuser={{idrac_user}} idracpswd={{idrac_passwd}} idracip={{idrac_ip}} subsystem=FW cmd={{item}}
    register: "fwinfo"
    ignore_errors: True
    with_items:
      - FirmwareInventory
    
  
    
  

    
  
      
    
      

      
        
      
  